### ISSUE TITLE
Not working for Now 2.0

### ISSUE THREAD

**Issue by baumland** [ImFeelingDucky/now-discordjs#1]
Hi, i tried deploying my bot using this template, it however refused to it because now v2 doesn't accept this template. Please update it.

**Comment by xtyrrell** [comment]
Hi there. Did you make sure you deployed with a `now.json` that specified `"version": 1`, and that it was in the same directory as where you ran the `now` command?

**Comment by baumland** [comment]
-

**Comment by baumland** [comment]
It worked, thanks alot!

**Comment by xtyrrell** [comment]
Glad it worked :) I'll add a note to remember to do this in the README

**Comment by baumland** [comment]
Version 1 is deprecated now, seems like you cant host a Bot 24/7 now

**Comment by xtyrrell** [comment]
That's unfortunately true! :( You can try Heroku or Glitch.com but I'm not sure either of those supports continuously-running servers :disappointed:

Good luck! And if you find something that works, feel free to update this guide.
