### ISSUE TITLE
ZEIT Now 1.0 Deprecation

### ISSUE THREAD

**Issue by mcsdevv** [ImFeelingDucky/now-discordjs#2]
Hello all,

On 03/04/2020, ZEIT sent an email to confirm the deprecation of the Now 1.0 platform. As of 01/05/2020, it will no longer be possible to create a new 1.0 deployment.

As a result of this, it would make sense to either change the target deployment environment to an alternative provider or archive the repository as `"version": 1` will no longer work.

**Comment by xtyrrell** [comment]
Thanks for the heads-up. I'll add a notice about this to the readme. I may be able to port this guide to another platform. If not, I think it makes sense to archive the repo.
